### ISSUE TITLE
How to remove a item from itemBuilder ?

### ISSUE THREAD

**Issue by indjec** [AbdulRahmanAlHamali/flutter_pagewise#101]
How to remove a particular item from the PagewiseListView?

**Comment by grishundel** [comment]
It is written that you can somehow create a custom list using this package, but I did not understand how to use it. So I did this by changing the package code. You can find it in "flutter\. pub-cache\hosted\pub.dartlang. org\flutter_pagewise-2.0.1\lib\flutter_pagewise.dart". There in the class PagewiseLoadController < T> extends ChangeNotifier I added:

```
void removeFromList(int index){
    this._loadedItems!.removeAt(index);
    notifyListeners();
  }
```

Next, without compiling, I just saved the file.
