### ISSUE TITLE
How to pass more parameters in PageWiseLoadController

### ISSUE THREAD

**Issue by indjec** [AbdulRahmanAlHamali/flutter_pagewise#105]
I want to pass an id  when i build the pagewiseloadcontroller.
```
final _pageLoadController = PagewiseLoadController(
  pageSize: 6,
  pageFuture: BackendService.getPage
);
```

This is the basic code given in the example, how can we pass more than one parameters in the getPage method?

**Comment by deandreamatias** [comment]
Hey @indjec I made this:
`        _pageLoadController = PagewiseLoadController<Result>(
          pageSize: 20,
          pageFuture: (int page) => model.loadList(
            textEditingController.text,
            page + 1,
            LocalizedApp.of(context)
                .delegate
                .currentLocale
                .languageCode
                .toString(),
          ),
        );
`
Maybe this code help you. Can see the entire app [here](https://github.com/deandreamatias/tv-randshow)
