### ISSUE TITLE
How to integrate RefreshIndicator

### ISSUE THREAD

**Issue by anderscheow** [AbdulRahmanAlHamali/flutter_pagewise#12]
Can you show me how to integrate RefreshIndicator where the Pagewise will reset it data

**Comment by AbdulRahmanAlHamali** [comment]
This is currently not available. However, I am rolling in a new update (hopefully tomorrow), which will provide a controller that you can use to reset, and do other useful functionality with the data

**Comment by anderscheow** [comment]
Well that's great, it would be useful for me

**Comment by AbdulRahmanAlHamali** [comment]
Hello, I pushed version 1.1.0, which should hopefully provide the features you are looking for. Would you kindly check it out?

**Comment by saikuamar** [comment]
how to do we add refresh indicator. i need a refresh indicator which looks great .please any example how to do it
thanks for the helpo

**Comment by yusufsafrudin** [comment]
Hello, Can you show me how to change value inside pagewise list like this
https://stackoverflow.com/questions/50044618/how-to-increment-counter-for-a-specific-list-item-in-flutter 
thank you
