### ISSUE TITLE
Dynamic constructor parameters aren't helpful

### ISSUE THREAD

**Issue by ResoDev** [AbdulRahmanAlHamali/flutter_pagewise#24]
First of all, thank you for this amazing library!

Constructors of PagewiseListView have only dynamic values while I see that Pagewise base class has them all properly typed. The fact that the class which is exposed to us doesn't have types for its parameters is not the best thing. Is it possible to add types even to the classes extending Pagewise?

**Comment by AbdulRahmanAlHamali** [comment]
yeah @ResoDev that's a good idea!

I will be pushing a release this weekend and will make sure to include it. Thank you!
