### ISSUE TITLE
New version 1.2.0 integration with Wordpress

### ISSUE THREAD

**Issue by raffaelecolleo** [AbdulRahmanAlHamali/flutter_pagewise#27]
Hi guys,
I've checked Your new version and it's a little confusing for me. Could You please explain me how do I integrate this with a JSON request that is paginated? 
What I mean is that I have a JSON request that should pull 1243 results, but I don't want then to be loaded at once. So the JSON request is called every time I get to the end of the 10 results I just pulled.

Does it make sense?

Thanks for Your time!

**Comment by raffaelecolleo** [comment]
{"status":"ok","total":10,"count_total":13145,"offset":0,"pages":1315,"posts":[{"id":60183,"wpcf-model-name":"CHEVROLET VERANEIO (1968)","wpcf-reference":"2B2EB145","wpcf-date-added-to-db":"06\/12\/2018","wpcf-main-image":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/2B2EB145-1.jpg","wpcf-image_2":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/2B2EB145-2.jpg","wpcf-image_3":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/2B2EB145-3.jpg","slug":"2b2eb145","guid":"https:\/\/www.mydomain.com\/2b2eb145","wpcf-country-code":"BR","wpcf-country":"Brazil","wpcf-model-type-code":"T7","wpcf-model-type":"Cars","wpcf-publisher-code":"EM","wpcf-publisher":"Eaglemoss","wpcf-scale-code":"S7","wpcf-scale":"1\/43"},{"id":60182,"wpcf-model-name":"HOLLAND COACH","wpcf-reference":"PB21PL","wpcf-date-added-to-db":"18\/02\/2019","wpcf-main-image":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/PB21PL-1.jpg","wpcf-image_2":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/PB21PL-2.jpg","wpcf-image_3":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/PB21PL-3.jpg","slug":"pb21pl","guid":"https:\/\/www.mydomain.com\/pb21pl","wpcf-country-code":"PL","wpcf-country":"Poland","wpcf-model-type-code":"S6","wpcf-model-type":"n\/a","wpcf-publisher-code":"DIT","wpcf-publisher":"DeAgostini IT","wpcf-scale-code":"S9","wpcf-scale":"1\/72"},{"id":60179,"wpcf-model-name":"PEGASO 12317","wpcf-reference":"6PEGE010","wpcf-date-added-to-db":"06\/12\/2018","wpcf-main-image":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6PEGE010-1.jpg","wpcf-image_2":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6PEGE010-2.jpg","wpcf-image_3":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6PEGE010-3.jpg","slug":"6pege010","guid":"https:\/\/www.mydomain.com\/6pege010","wpcf-country-code":"SP","wpcf-country":"Spain","wpcf-model-type-code":"T14","wpcf-model-type":"Trucks","wpcf-publisher-code":"HSB","wpcf-publisher":"Salvat - Hachette SP\/BR","wpcf-scale-code":null,"wpcf-scale":"- Select -"},{"id":60176,"wpcf-model-name":"NISSAN CHERRY COUPE X-1R (1973)","wpcf-reference":"6J24J061","wpcf-date-added-to-db":"04\/02\/2019","wpcf-main-image":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6J24J061-1.jpg","wpcf-image_2":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6J24J061-2.jpg","wpcf-image_3":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6J24J061-3.jpg","slug":"6j24j061","guid":"https:\/\/www.mydomain.com\/6j24j061","wpcf-country-code":"JP","wpcf-country":"Japan","wpcf-model-type-code":"T7","wpcf-model-type":"Cars","wpcf-publisher-code":"HJP","wpcf-publisher":"Hachette JP","wpcf-scale-code":"S5","wpcf-scale":"1\/24"},{"id":60174,"wpcf-model-name":"DODGE GTX - OSCAR ANGELETTI - 1986","wpcf-reference":"TUC28AR","wpcf-date-added-to-db":"04\/02\/2019","wpcf-main-image":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/TUC28AR-1.jpg","wpcf-image_2":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/TUC28AR-2.jpg","wpcf-image_3":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/TUC28AR-3.jpg","slug":"tuc28ar","guid":"https:\/\/www.mydomain.com\/tuc28ar","wpcf-country-code":"AR","wpcf-country":"n\/a","wpcf-model-type-code":"T7","wpcf-model-type":"Cars","wpcf-publisher-code":"0","wpcf-publisher":"n\/a","wpcf-scale-code":"S7","wpcf-scale":"1\/43"},{"id":60173,"wpcf-model-name":"CHAR B1 BIS 28EME BATAILLON DE CHARS DE COMBAT FRANCE - MAY 1940","wpcf-reference":"TN83SP","wpcf-date-added-to-db":"17\/02\/2019","wpcf-main-image":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/TN83SP-1.jpg","wpcf-image_2":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/TN83SP-2.jpg","wpcf-image_3":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/TN83SP-3.jpg","slug":"tn83sp","guid":"https:\/\/www.mydomain.com\/tn83sp","wpcf-country-code":"SP","wpcf-country":"Spain","wpcf-model-type-code":"T12","wpcf-model-type":"Tanks","wpcf-publisher-code":"0","wpcf-publisher":"n\/a","wpcf-scale-code":"S7","wpcf-scale":"1\/43"},{"id":60172,"wpcf-model-name":"CHAR B1 BIS 28EME BATAILLON DE CHARS DE COMBAT FRANCE - MAY 1940","wpcf-reference":"TN83FR","wpcf-date-added-to-db":"21\/02\/2019","wpcf-main-image":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/TN83FR-1.jpg","wpcf-image_2":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/TN83FR-2.jpg","wpcf-image_3":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/TN83FR-3.jpg","slug":"tn83fr","guid":"https:\/\/www.mydomain.com\/tn83fr","wpcf-country-code":"FR","wpcf-country":"France","wpcf-model-type-code":"T12","wpcf-model-type":"Tanks","wpcf-publisher-code":"PLA","wpcf-publisher":"Planeta","wpcf-scale-code":"S7","wpcf-scale":"1\/43"},{"id":60171,"wpcf-model-name":"FIAT 1500 MULTICARGA - SERGI AUTOMOTORES (1965)","wpcf-reference":"6SVCAR023","wpcf-date-added-to-db":"21\/02\/2019","wpcf-main-image":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6SVCAR023-1.jpg","wpcf-image_2":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6SVCAR023-2.jpg","wpcf-image_3":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6SVCAR023-3.jpg","slug":"6svcar023","guid":"https:\/\/www.mydomain.com\/6svcar023","wpcf-country-code":"AG","wpcf-country":"Argentina","wpcf-model-type-code":"T7","wpcf-model-type":"Cars","wpcf-publisher-code":"HSB","wpcf-publisher":"Salvat - Hachette SP\/BR","wpcf-scale-code":"S7","wpcf-scale":"1\/43"},{"id":60170,"wpcf-model-name":"NISSAN VERSA (2012)","wpcf-reference":"MXC70MX","wpcf-date-added-to-db":"18\/02\/2019","wpcf-main-image":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/MXC70MX-1.jpg","wpcf-image_2":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/MXC70MX-2.jpg","wpcf-image_3":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/MXC70MX-3.jpg","slug":"mxc70mx","guid":"https:\/\/www.mydomain.com\/mxc70mx","wpcf-country-code":"MX","wpcf-country":"Mexico","wpcf-model-type-code":"T7","wpcf-model-type":"Cars","wpcf-publisher-code":"PLA","wpcf-publisher":"Planeta","wpcf-scale-code":"S7","wpcf-scale":"1\/43"},{"id":60169,"wpcf-model-name":"\u0413\u0417\u0417-\u041c20 \u00ab\u041f\u041e\u0411\u0415\u0414\u0410\u00bb \u041a\u0410\u0411\u0420\u0418\u041e\u041b\u0415\u0422","wpcf-reference":"6R24R027","wpcf-date-added-to-db":"21\/02\/2019","wpcf-main-image":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6R24R027-1.jpg","wpcf-image_2":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6R24R027-2.jpg","wpcf-image_3":"https:\/\/www.mydomain.com\/wp-content\/models\/2018\/11\/6R24R027-3.jpg","slug":"6r24r027","guid":"https:\/\/www.mydomain.com\/6r24r027","wpcf-country-code":"RU","wpcf-country":"Russia","wpcf-model-type-code":"T7","wpcf-model-type":"Cars","wpcf-publisher-code":"HDR","wpcf-publisher":"Hachette DE\/RU","wpcf-scale-code":"S5","wpcf-scale":"1\/24"}]}

**Comment by AbdulRahmanAlHamali** [comment]
Hello, I apologize I couldn't answer any sooner.

Inside your JSON structure, you have an array called posts. You should return this array in the `pageFuture` callback. Does this make sense?

**Comment by AbdulRahmanAlHamali** [comment]
Hello @raffaelecolleo,

Is your problem solved?

**Comment by AbdulRahmanAlHamali** [comment]
Closing due to lack of response. Please feel free to reopen the issue if you are still facing it
