### ISSUE TITLE
Suggestion: use controller pattern

### ISSUE THREAD

**Issue by szotp** [AbdulRahmanAlHamali/flutter_pagewise#3]
The plugin works nice but it would be good to have info have many pages have been loaded, etc. Also setup is kind of annoying because you have to pass bunch of callback which are dynamic for some reason. 

Flutter uses Controller pattern, for example TextEditingController that stores this kind of data, so that it can be accessed from other widges. Something like this would probably work:
```
abstract class PageLoaderController<T> extends ChangeNotifier {
  Future<List<dynamic>> loadPage(int index);
  int get totalCount;
  int get pageSize;
}
```

**Comment by AbdulRahmanAlHamali** [comment]
That is a good idea! I'm actually working on a restructuring of the whole widget, to make it more efficient, and to make it not need a totalCount parameter. I will try to include the controller pattern with those upcoming changes.

Thank you for the suggestion!

**Comment by szotp** [comment]
Good luck then.

**Comment by anderscheow** [comment]
Can you add a fallback or error widget if snapshot return error, so that the fallback or error widget which has a button to retry the API call

**Comment by AbdulRahmanAlHamali** [comment]
Thank you for your suggestion. I am sorry it took that long to implement, but I had an overwhelming couple of months.

I did implement the controller pattern indeed and I think it looks great! Do you mind checking it out?

**Comment by szotp** [comment]
Hi @AbdulRahmanAlHamali this looks nice, thanks for following my suggestion. There is a gotcha related to ChangeNotifier because you need to check if it was not replaced in didUpdateWidget method. You can see how flutter team did it here:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_field.dart#L455

**Comment by AbdulRahmanAlHamali** [comment]
Ohh thank you for the note! I will fix that today!

**Comment by AbdulRahmanAlHamali** [comment]
And done! Thank you again @szotp!
