### ISSUE TITLE
Providing own PagewiseLoadController and using reset() messes up PageIndex

### ISSUE THREAD

**Issue by Blendstrup** [AbdulRahmanAlHamali/flutter_pagewise#30]
Hey there!

First of all, this is an awesome package! It has really saved me a ton of work. Thank you very much for the work you have done.

However, I have run into some problems using this package. I have recently changed my code so that my list (using Pagewise) is now using my own PagewiseLoadController that I have stored in a scoped model. I have done this in order to be able to reset the list/controller when I change an aspect of whatever should be fetched and displayed in the list (I'm making a simple movie app, and when I change the category of movies to fetch, I have to reset the Pagewise controller so that it can start over and start with the future that is now fetched using the new category).

When the app is first started there's no problems, and scrolling down fetches the next pages as expected. However, the problem occurs when I change the category (thereby also calling myPageWiseController.reset() ), which then fetches the first page with the new category correctly, but scrolling down makes the first fetched page loop, so that its basically just an infinite list of the movies from the first fetched page displaying over and over.

I've tried printing the PageIndex whenever a new fetch occurs from scrolling to the bottom, and I can see that the PageIndex stops incrementing after I change the category and reset the controller, but before that (when the app is first started) it increments totally fine. A look at the debug console shows the following:

> Launching lib\main.dart on Pixel in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/flutter ( 4688): 1
I/flutter ( 4688): 2
I/flutter ( 4688): 3
I/flutter ( 4688): 4
I/flutter ( 4688): 5

Here I change the category to something else than what the app initially starts with.

> I/flutter ( 4688): 1

Initially it fetches the first page fine, as shown by the 1 above, but after scrolling to the bottom, the following is printed.

> I/chatty ( 4688): uid=10369(com.example.myapp) 1.ui identical 7 lines
I/flutter ( 4688): 1

I don't know why that 1 above shows, it is not because of any change in the app, other than scrolling, the category is still the same.

When I change the category to something else again, the 1 below is shown and the first page with the new category is fetched normally, after which the same error shows up.

> I/flutter ( 4688): 1
I/chatty  ( 4688): uid=10369(com.example.myapp) 1.ui identical 8 lines
Application finished.
Exited (sigint)

Here is the relevant code:

My own PageWiseLoadController setup:
```
pageLoadController = PagewiseLoadController(
      pageSize: 20,
      pageFuture: (int pageIndex) => fetchMovies(pageIndex),
    );
```

Resetting the controller/list:
```
void resetList() {
    _pageLoadController.reset();
  }
```

The fetchMovies method (I'm incrementing the pageIndex, simply because the pageIndex starts at 0 but I have to start it at 1 for the fetching to work):
```
Future<List<Results>> fetchMovies(int pageIndex) async {
    pageIndex++;
    print(pageIndex);

    String category = (_categoryNow != null) ? _categoryNow.path : "popular";
    String url = "$baseUrl$category?api_key=$apiKey&page=$pageIndex&region=$_region";

    var response = await http.get(url);
    var decodeJson = jsonDecode(response.body);

    Movie newContent = Movie.fromJson(decodeJson);
    return newContent.results;
  }
```

My widget for the list:
```
class ContentList extends StatelessWidget {
  Widget build(BuildContext context) {
    return ScopedModelDescendant<ContentModel>(
      builder: (context, child, model) {
        return PagewiseListView(
          pageLoadController: model.pageLoadController,
          itemBuilder: (context, entry, _) => MovieCard(entry),
          noItemsFoundBuilder: (context) => Text('No Items Found'),
          retryBuilder: (context, callback) {
            return RaisedButton(
              child: Text('Retry'),
              onPressed: () => model.resetList(),
            );
          },
        );
      },
    );
  }
}
```

I've tried to describe the issue as best as I can, and hopefully I provided enough information/code for you to understand it.

**Comment by lifenautjoe** [comment]
Experiencing same issue. None of the proposed hacks worked either...

**Comment by lifenautjoe** [comment]
I suspect this has something to do with not cleaning up listeners.

**Comment by AbdulRahmanAlHamali** [comment]
Understood, I will try my best to look into it over the weekend.

If anyone is interested in helping and submitting a pull request, it would be great too! I am currently looking for collaborators for the project, because of my lack of time.

**Comment by Blendstrup** [comment]
@AbdulRahmanAlHamali awesome, thanks for the help. I'll try a few things out as well.

If I had the abilities I would love to help out, but I have a very limited experience with programming, and only started Flutter a few months ago. Sorry that I can't help, but I will cross my fingers in the hopes that you'll find a helping hand soon.

**Comment by AbdulRahmanAlHamali** [comment]
@Blendstrup Thank you! I hope so too!

**Comment by Blendstrup** [comment]
Hey @AbdulRahmanAlHamali 

So I've been working quite a bit on my code these last few days, and somehow I've fixed this issue.

Unfortunately I don't know what I did to fix it, because I've change a whole bunch of code. My best guess would be that it was solved when I updated the data models I had for the fetched json, because I've given those a major overhaul. Nevertheless I can't be certain that this is actually what solved it.

**Comment by Blendstrup** [comment]
*Solved it mostly

It seems that sometimes it loads the first fetched page twice, but then loads normally afterwards.

Not sure if this is because the pageIndex isn't incremented for the second fetch, but I suspect that might be the case.

**Comment by AbdulRahmanAlHamali** [comment]
Hello @Blendstrup, I finally got some time to look at the issue, but I cannot seem to replicate your problem. I made an example where I keep switching categories and fetching different data, and I didn't face the problem of the first page sticking and not changing.

I did not use a ScopedModel, and I am not really sure what that is as I have been away from the flutter world for a couple of months, but it might not be playing well with Pagewise.

@sjmcdowall interested in taking a shot at this? Do you have experience with Scoped Models?

**Comment by Blendstrup** [comment]
It doesn't always happen when using "official" categories from TMDb, like fetching top rated or popular movies, but it seems to always happen when fetching search results.

I've found that with "official" categories it happens often if one switches category and immediately scrolls to the bottom of the list. So at first it loads the initial 20 items, and then if you scroll down fast to the bottom of those, where the list is then supposed to load the next 20 items, it will duplicate the first 20 pages (without any loading at all) so you actually have to scroll past 40 items (the first 20 items twice in a row) before it starts loading the next batch.

Scoped models are just a simple way to do state management, sort of like using an inherited widget, and since it resets the PagewiseLoadController every time a category switch occurs, I don't see how this could interfere with the list/fetching, but I'll try to test it without the scoped model to see if it makes any difference.

It could just be that there is something wrong with my code, although I wouldn't know what it could be, but I'll make sure to try a few things out and report back if I come closer to solving the issue.

**Comment by sjmcdowall** [comment]
Agree that ScopedModel is very unlikely the culprit here -- I've used them quite a bit and never saw and odd thing like this.  If you can get a consistent (and hopefully GitHub project) that can reproduce the error that would be great!

**Comment by Blendstrup** [comment]
@sjmcdowall I'm not quite sure what you mean, I don't really use GitHub much, but I can upload my project to GitHub so that you can take a look, if that's what you're asking?

I could also do a quick screen recording on my phone showing the problem in action, if that would help?


Also, I don't know if this affects anything or is of any use, but I am developing my app using a physical device (an original Google Pixel) connected to my computer (win10) and I use VS code to write the app.

**Comment by Blendstrup** [comment]
Alright, so you want me to kind of extract the relevant code for this issue, and make it into its own smaller app, and then give you that code along with a guide on what to do to reproduce the issue?

(Sorry for the many questions, English is not my first language, and I want to make sure that I give you what you actually need)

**Comment by sjmcdowall** [comment]
That would be perfect @Blendstrup !! Thank you.

**Comment by Blendstrup** [comment]
Hey @sjmcdowall 

I believe I've uploaded the project correctly, you can find it here: 
https://github.com/Blendstrup/Flutter-PageWise-Duplication-Issue

I've stripped as much code as possible while still keeping the option for fetching and displaying movies and well as changing the category. I've also kept the search functionality, since this also produces the issue. I've commented a bit throughout the code, sometimes the comments are possibly a little redundant or too simple, but I wanted to help you understand the code as best as I could, even though I suspect you are probably quite good at flutter/dart.


Instructions for reproducing issue:

1. Open app (make sure to input an TMDb api key in content_model.dart first!)
2. Change category to any other (use icon in top right corner to show the category menu)
3. Scroll down fast until the list displays an circular progress indicator

In the debug console you should see that it printed PageIndex: 1 and PageIndex: 3 but not 2.
You will also see that the first batch of fetched movies is displayed twice in a row, but that afterwards it will load the rest of the pages perfectly fine.


Another way for reproducing the issue:

1. Open app (make sure to input an TMDb api key in content_model.dart first!)
2. Search for anything (I searched 'thanks') using the search icon in the appbar
3. Scroll at a normal pace and you should experience the issue aswell

Again, it should print 1 and 3, but skip 2 and duplicate the first fetched batch of movies.


If you've got any questions or need my help for anything, feel free to reach out and I'll get back as quick as possible. Hopefully you can tell if it's me who's doing something wrong, or if it's Pagewise.

**Comment by Blendstrup** [comment]
Oh by the way:
- The folder 'api' contains a data model for handling the fetched json
- The folder 'models' contains the scoped model (only one for this stripped app)
- The folder 'screens' contains the widgets that make up the screens that are shown to the user, in this case just a backdrop widget
- The folder 'widgets' contains... Widgets.

**Comment by AbdulRahmanAlHamali** [comment]
Thank you for sharing all this info! I will look into this tonight hopefully, and once solved, we can push a new version

**Comment by AbdulRahmanAlHamali** [comment]
OK I think I caught the error. There seems to be some cases (not sure why they're happening) where the `_itemBuilder` is called more than once. Which is resulting in calling `pageFuture` multiple times. What we need to do is provide some sort of mutex, that checks whether we are already loading this page, and if so, disallows us from calling the action again.

I will work on this hopefully tonight, and will push a fix, but if anyone is interested, feel free to beat me to it!

**Comment by sjmcdowall** [comment]
I’ve seen this behavior before with itemBuilders .. sadly .. but only itemBuilders and not if the children are static ..

And yeah .. need to keep a bool flag handy so it’s not repeated .. that’s the work around I did in the other project 

Alas - Internet here is god awful til I switch hotels tomorrow afternoon
