### ISSUE TITLE
Page wise controller reset does not return a Future

### ISSUE THREAD

**Issue by lifenautjoe** [AbdulRahmanAlHamali/flutter_pagewise#32]
In the readme its stated that the reset method could be used together with the `RefreshIndicator`, the refresh indicator however expects the `onRefresh` method to return a `Future`. The `PagewiseLoadController` `reset` methods returns void as contrary to the example in the readme.

**Comment by AbdulRahmanAlHamali** [comment]
This hasn't caused a problem before, but I think it should be solved by specifying a type for reset, which is Future<void>. I will implement the fix in the weekend along with other fixes.

Thank you for reporting!
