### ISSUE TITLE
exception if there is only items <= pageSize

### ISSUE THREAD

**Issue by rakeshlanjewarwork** [AbdulRahmanAlHamali/flutter_pagewise#35]
This pluginn is working great except this exception where there is one one item

Code:- 

```dart
return Scaffold(
      backgroundColor: Colors.white,
      appBar: new AppBar(
        centerTitle: true,
        title: new Text(
          widget.category.name,
          style: TextStyle(fontWeight: FontWeight.normal),
        ),
        leading: IconButton(
          icon: Icon(Icons.arrow_back_ios),
          onPressed: () => Navigator.of(context).pop(),
        ),
        actions: [
          PopupMenuButton<SortBy>(
            icon: Icon(Icons.sort_by_alpha),
            onSelected: changeSort,
            itemBuilder: (BuildContext context) => <PopupMenuItem<SortBy>>[
                  PopupMenuItem<SortBy>(
                    value: SortBy.AZ,
                    child: Text("A - Z"),
                  ),
                  PopupMenuItem<SortBy>(
                    value: SortBy.ZA,
                    child: Text("Z - A"),
                  ),
                ],
            elevation: 10.0,
            tooltip: "Sort By",
          ),
        ],
      ),
      body: Container(
        color: Colors.white,
        child: PagewiseGridView.count(
          crossAxisCount:
              MediaQuery.of(context).orientation == Orientation.portrait
                  ? 2
                  : 4,
          mainAxisSpacing: 4.0,
          crossAxisSpacing: 4.0,
          itemBuilder: (context, entry, _) {
            return ProductCard(entry);
          },
          pageLoadController: pageLoadController,
          childAspectRatio: 1.0,
          noItemsFoundBuilder: (context) {
            return Container(
              color: Colors.white,
              child: Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Icon(
                        Icons.device_unknown,
                        color: Colors.black26,
                        size: 24,
                      ),
                    ),
                    Text(
                      "No products matching to this criteria",
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.black26,
                      ),
                    ),
                  ],
                ),
              ),
            );
          },
          showRetry: true,
          loadingBuilder: (context) {
            return Row(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                CircularProgressIndicator(),
                SizedBox(
                  width: 20.0,
                ),
                Text('Loading...'),
              ],
            );
          },
        ),
      ),
    );
```

Exception Log:- 
I/flutter (25161): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (25161): The following assertion was thrown during performLayout():
I/flutter (25161): SliverGeometry is not valid: The "maxPaintExtent" is less than the "paintExtent".
I/flutter (25161): The maxPaintExtent is 178.0, but the paintExtent is 360.0. By definition, a sliver can't paint more
I/flutter (25161): than the maximum that it can paint!
I/flutter (25161): The RenderSliver that returned the offending geometry was:
I/flutter (25161):   RenderSliverGrid#ba222 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (25161):   creator: SliverGrid ← MediaQuery ← SliverPadding ← Viewport ← _ScrollableScope ←
I/flutter (25161):   IgnorePointer-[GlobalKey#bcd2a] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (25161):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#e36d5] ←
I/flutter (25161):   _ScrollSemantics-[GlobalKey#e2845] ← RepaintBoundary ← ⋯
I/flutter (25161):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter (25161):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (25161):   scrollOffset: 0.0, remainingPaintExtent: 596.7, crossAxisExtent: 360.0, crossAxisDirection:
I/flutter (25161):   AxisDirection.right, viewportMainAxisExtent: 596.7, remainingCacheExtent: 846.7 cacheOrigin: 0.0 )
I/flutter (25161):   geometry: SliverGeometry(scrollExtent: 178.0, paintExtent: 360.0, maxPaintExtent: 178.0,
I/flutter (25161):   hasVisualOverflow: true, cacheExtent: 360.0)
I/flutter (25161):   currently live children: 0 to 1
I/flutter (25161): 
I/flutter (25161): When the exception was thrown, this was the stack:
I/flutter (25161): #0      SliverGeometry.debugAssertIsValid.<anonymous closure>.verify (package:flutter/src/rendering/sliver.dart:674:9)
I/flutter (25161): #1      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:694:15)
I/flutter (25161): #2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:706:6)
I/flutter (25161): #3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:1061:21)
I/flutter (25161): #4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1636:19)
I/flutter (25161): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1636:67)
I/flutter (25161): #6      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (25161): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25161): #8      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (25161): #9      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter (25161): #10     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter (25161): #11     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter (25161): #12     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter (25161): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (25161): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (25161): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (25161): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (25161): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (25161): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (25161): #22     _invoke (dart:ui/hooks.dart:156:10)
I/flutter (25161): #23     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (25161): (elided 3 frames from package dart:async)
I/flutter (25161): 
I/flutter (25161): The following RenderObject was being processed when the exception was fired:
I/flutter (25161):   RenderSliverGrid#ba222 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (25161):   creator: SliverGrid ← MediaQuery ← SliverPadding ← Viewport ← _ScrollableScope ←
I/flutter (25161):   IgnorePointer-[GlobalKey#bcd2a] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (25161):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#e36d5] ←
I/flutter (25161):   _ScrollSemantics-[GlobalKey#e2845] ← RepaintBoundary ← ⋯
I/flutter (25161):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter (25161):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (25161):   scrollOffset: 0.0, remainingPaintExtent: 596.7, crossAxisExtent: 360.0, crossAxisDirection:
I/flutter (25161):   AxisDirection.right, viewportMainAxisExtent: 596.7, remainingCacheExtent: 846.7 cacheOrigin: 0.0 )
I/flutter (25161):   geometry: SliverGeometry(scrollExtent: 178.0, paintExtent: 360.0, maxPaintExtent: 178.0,
I/flutter (25161):   hasVisualOverflow: true, cacheExtent: 360.0)
I/flutter (25161):   currently live children: 0 to 1
I/flutter (25161): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (25161):   RenderIndexedSemantics#04bae NEEDS-PAINT
I/flutter (25161):     RenderRepaintBoundary#af3ad NEEDS-PAINT
I/flutter (25161):       RenderSemanticsGestureHandler#a7dbb NEEDS-PAINT
I/flutter (25161):         RenderPointerListener#132a7 NEEDS-PAINT
I/flutter (25161):           RenderSemanticsAnnotations#ef278 NEEDS-PAINT
I/flutter (25161):   RenderIndexedSemantics#57f8f NEEDS-PAINT
I/flutter (25161):     RenderRepaintBoundary#f31a0 NEEDS-PAINT
I/flutter (25161):       RenderPadding#3867c NEEDS-PAINT
I/flutter (25161):         RenderPositionedBox#bb1ec NEEDS-PAINT
I/flutter (25161):           RenderFlex#48555 relayoutBoundary=up1 NEEDS-PAINT
I/flutter (25161): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (25161): App is in debug mode

**Comment by AbdulRahmanAlHamali** [comment]
Yes this is a known issue.

The thing is that, the way Pagewise is designed: the loader is part of the elements of the GridView, so when the number of the elements is less than the pagesize, I am forcing the loader to go down to the next level, which is why the error is happening. I will solve that soon hopefully

**Comment by rakeshlanjewarwork** [comment]
Please let us know when the new version is releasing ?

**Comment by AbdulRahmanAlHamali** [comment]
This week hopefully, we are finalizing a few more bugs and will release
