### ISSUE TITLE
Feature request:- can pass additional data with pageFuture

### ISSUE THREAD

**Issue by rakeshlanjewarwork** [AbdulRahmanAlHamali/flutter_pagewise#36]
Can we send additional data to pageFuture so we can make it more reusable.

**Comment by AbdulRahmanAlHamali** [comment]
I don't mind that, but what sort of data might you need?

**Comment by sjmcdowall** [comment]
I was thinking the same thing -- @rakeshlanjewarwork -- that is a pretty generic request.  Need more details -- can you provide user stories/use cases on what exactly you are looking for ?  How do you visualize it working?

**Comment by rakeshlanjewarwork** [comment]
make it dynamic so i can pass any data,

This will be useful when we are making http.

**Comment by rakeshlanjewarwork** [comment]
It will be helpful in this Scenario:- 

```dart
Future<List> getCategoryPage(pageIndex) async {
    List<Product> categoryProducts = [];
    await http
        .get(Application.url +
        "/get_products_by_category/${widget.category.categoryId}/$pageIndex/$sortBy")
        .then((response) {
      if (response.statusCode == 200) {
        List js = json.decode(response.body);
        js.forEach(
              (product) {
            Application.mainModel.addToProductsList(product);
            categoryProducts.add(Product.fromJson(product));
          },
        );
      }
    }).catchError((error) {
      throw (error);
    });

    return categoryProducts;
  }
```
now if we want to separate the code from UI like we do in scoped model.

now i have to access data like this widget.category.categoryId

**Comment by AbdulRahmanAlHamali** [comment]
I see, but in this case, wouldn't make more sense to do the following:
```
pageFuture: (pageIndex) => getCategoryPage(pageIndex, widget.category.categoryId)
```

And your `getCategoryPage` would accept a `pageIndex`, and a `categoryId`, achieving the required seperation from UI. What do you think?

**Comment by rakeshlanjewarwork** [comment]
Thank you ! 
Thats what i want !!!
