### ISSUE TITLE
Support for retry all failed request

### ISSUE THREAD

**Issue by anderscheow** [AbdulRahmanAlHamali/flutter_pagewise#4]
When I clicked on the refresh indicator on the error builder, it only retry the particular failed request. I suggest it should retry for all the failed request or at least add a flag to control that.

**Comment by AbdulRahmanAlHamali** [comment]
Yeah, that is true.

In the new version that I'm working on that won't be a problem, because only one refresh widget will be displayed anyway, unlike the current, inefficient version

**Comment by AbdulRahmanAlHamali** [comment]
Hello @anderscheow , I apologize for the late answer. 

I rewrote Pagewise from scratch, and now it stops scrolling until the next page is loaded, and shows only one loading at a time.

I will close this as fixed in version 1.0.0
