### ISSUE TITLE
initial load not triggered, ListView

### ISSUE THREAD

**Issue by sensiblearts** [AbdulRahmanAlHamali/flutter_pagewise#47]
Greetings,

The package seems to be working very well for me except for one issue: The list is initially blank and I have to click the retry button to force the initialization (pageFuture for page 0). 
After that, it pageFuture works just fine.

Is there a method to force initialization? Or am I doing something wrong?

Thanks.

Here is my code:

```dart
// .. Stateful widget...

class _EntriesState extends State<Entries> {
  static const PAGE_SIZE = 3;
  LabeledEntriesModel _model;  // a ScopedModel
  List<Entry> _entries = [];

  Future<List<Entry>> _getEntries(pageIndex) async {
    int offset = pageIndex * PAGE_SIZE;
    int limit = PAGE_SIZE;
    return _entries.sublist(offset, offset + limit);
  }

  Widget _buildEntryList(LabeledEntriesModel model) {
    return PagewiseListView(
      pageSize: PAGE_SIZE,
      padding: EdgeInsets.all(15.0),
      itemBuilder: (context, item, index) => EntryCard(entry: item),
      pageFuture: (pageIndex) => _getEntries(pageIndex),
    );
  }

  @override
  Widget build(BuildContext context) {
    return ScopedModelDescendant<LabeledEntriesModel>(
      builder: (context, Widget child, LabeledEntriesModel model) {
        _model = model;
        _entries = _model.entriesForLabel(_model.curLabel);
        return _buildEntryList(model);
      },
    );
  }
}

```

**Comment by sensiblearts** [comment]
Never mind. 
My entire widget (that contains yours) is being initialized too soon. I need to figure out Flutter's initialization logic. It's not your package. Sorry to bother.
DA

**Comment by sjmcdowall** [comment]
StatefulWidget??  

Then it’s initState. .. didChangeDrepencies .. build() with the occasional other method .. can’t remember ..

What’s your current code ?
