### ISSUE TITLE
Give access to retry()

### ISSUE THREAD

**Issue by anderscheow** [AbdulRahmanAlHamali/flutter_pagewise#5]
In order to build a custom RetryWidget, we need access to retry() method to retry the request

**Comment by AbdulRahmanAlHamali** [comment]
Yes, the retryBuilder is by default provided with two parameters: 

* The BuildContext
* And a function for you to call to retry.

For example:

```
(context, retryCallback) {
  return RaisedButton(
    onPressed: () {
      retryCallback();
    }
  );
}
