### ISSUE TITLE
Dart SDK version Error

### ISSUE THREAD

**Issue by mabinici** [AbdulRahmanAlHamali/flutter_pagewise#50]
Running "flutter packages get" in app...                         
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because app depends on flutter_pagewise >=1.2.2 which requires SDK version >=2.1.0 <3.0.0, version solving failed.
 
pub get failed (1)

**Comment by sjmcdowall** [comment]
I just make a PR on the Develop branch to fix this.  Give it a try and if it works I'll Merge and Pub.. (I tried and seems fine for my project)

**Comment by ccbenavides** [comment]
the same error.

**Comment by sjmcdowall** [comment]
@ccbenavides are you using the develop branch within the pubspec??  Can you show the error?

**Comment by RecherJ** [comment]
I just fixed this by changing sdk version to `sdk: ">=2.1.0-dev.9.4 <3.0.0"`, this is temporary solution.

**Comment by ehhc** [comment]
if you do `flutter upgrade` first, it is fixed by now :)

**Comment by sjmcdowall** [comment]
@ehhc -- Yes, saved by the upgrade!  LOL
