### ISSUE TITLE
Length called on Null ERROR

### ISSUE THREAD

**Issue by asapJ** [AbdulRahmanAlHamali/flutter_pagewise#56]
I followed the examples stated carefully but each time I try to use the plugin,  my future completes with data successfully(i could log them to console ) but then I get the length called on Null error. On checking error stack It pointed to a line With

`Page.lenght <= another test case here`

But looking at this plugin,  there's no provision for page length,  So definitely that value might just b null,  or is there something I am missing ?  

Also my Code is almost as exact as your example below .
`Class PagewiseListViewExample extends StatelessWidget {
  static const int PAGE_SIZE = 10;

  @override
  Widget build(BuildContext context) {
    return PagewiseListView(
        pageSize: PAGE_SIZE,
        itemBuilder: this._itemBuilder,
        pageFuture: (pageIndex) =>
            BackendService.getPosts(pageIndex * PAGE_SIZE, PAGE_SIZE));
  }

  Widget _itemBuilder(context, PostModel entry, _) {
    return Column(
      children: <Widget>[
        ListTile(
          leading: Icon(
            Icons.person,
            color: Colors.brown[200],
          ),
          title: Text(entry.title),
          subtitle: Text(entry.body),
        ),
        Divider()
      ],
    );
  }
}`

**Comment by asapJ** [comment]
@AbdulRahmanAlHamali

**Comment by sjmcdowall** [comment]
What line # did it point to? Posting part of the error stack would be handy.  The line you highlighted appears to be a typo .. since it should be .length  not .lenght  ...

**Comment by asapJ** [comment]
error log



D/GraphicBuffer(30454): register, handle(0x8947e8c0) (w:720 h:1198 s:720 f:0x1 u:f02)
I/zygote  (30454): Do partial code cache collection, code=61KB, data=53KB
I/zygote  (30454): After code cache collection, code=61KB, data=53KB
I/zygote  (30454): Increasing code cache capacity to 256KB
I/System.out(30454): port:5054
I/flutter (30454): [http://test.natterbase.com:5054/, FunctionId@922369048, FunctionId@922369048]
I/flutter (30454): Socket Statusconnect
D/FlutterSocketIoPlugin: SocketIO(30454): connect: []
I/flutter (30454): {success: true, message: Successfully fetching inventories, data: {totalProducts: 4, productsOutOfStock: 0, productsInStock: 4}}
I/flutter (30454): {success: true, message: Successfully fetching inventories, data: {totalProducts: 4, productsOutOfStock: 0, productsInStock: 4}}
E/flutter (30454): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null.
E/flutter (30454): Receiver: null
E/flutter (30454): Tried calling: length
E/flutter (30454): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (30454): #1      PagewiseLoadController.fetchNewPage 
package:flutter_pagewise/flutter_pagewise.dart:475
E/flutter (30454): <asynchronous suspension>
E/flutter (30454): #2      PagewiseState._itemBuilder 
package:flutter_pagewise/flutter_pagewise.dart:270
E/flutter (30454): #3      SliverChildBuilderDelegate.build 
package:flutter/…/widgets/sliver.dart:398
E/flutter (30454): #4      SliverMultiBoxAdaptorElement._build.<anonymous closure> 
package:flutter/…/widgets/sliver.dart:1002
E/flutter (30454): #5      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:137:29)
E/flutter (30454): #6      SliverMultiBoxAdaptorElement._build 
package:flutter/…/widgets/sliver.dart:1002
E/flutter (30454): #7      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> 
package:flutter/…/widgets/sliver.dart:1015
E/flutter (30454): #8      BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2253
E/flutter (30454): #9      SliverMultiBoxAdaptorElement.createChild 
package:flutter/…/widgets/sliver.dart:1008
E/flutter (30454): #10     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>

**Comment by asapJ** [comment]
error log 


E/flutter (30454): Receiver: null
E/flutter (30454): Tried calling: length
E/flutter (30454): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (30454): #1      PagewiseLoadController.fetchNewPage 
package:flutter_pagewise/flutter_pagewise.dart:475
E/flutter (30454): <asynchronous suspension>
E/flutter (30454): #2      PagewiseState._itemBuilder 
package:flutter_pagewise/flutter_pagewise.dart:270
E/flutter (30454): #3      SliverChildBuilderDelegate.build 
package:flutter/…/widgets/sliver.dart:398
E/flutter (30454): #4      SliverMultiBoxAdaptorElement._build.<anonymous closure> 
package:flutter/…/widgets/sliver.dart:1002
E/flutter (30454): #5      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:137:29)
E/flutter (30454): #6      SliverMultiBoxAdaptorElement._build 
package:flutter/…/widgets/sliver.dart:1002
E/flutter (30454): #7      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> 
package:flutter/…/widgets/sliver.dart:1015
E/flutter (30454): #8      BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2253
E/flutter (30454): #9      SliverMultiBoxAdaptorElement.createChild 
package:flutter/…/widgets/sliver.dart:1008
E/flutter (30454): #10     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>

**Comment by sjmcdowall** [comment]
Thanks for the logs -- very helpful!  I'll see if I can take a look today or tomororw -- or if @KaYBlitZ wants to take a shot at it...

**Comment by sjmcdowall** [comment]
I submitted a PR to fix this -- you can give it a whirl early by pointing your pubspec.yaml to my fork & the develop branch ...

**Comment by sjmcdowall** [comment]
Fixed in latest release

**Comment by asapJ** [comment]
Fix  confirmed
