### ISSUE TITLE
Can't publish new version

### ISSUE THREAD

**Issue by sjmcdowall** [AbdulRahmanAlHamali/flutter_pagewise#59]
@AbdulRahmanAlHamali -- I just tried to publish the latest version and got this:

UnauthorizedAccess: Unauthorized user: sjm@hawoods.org is not allowed to upload versions to package flutter_pagewise..

Can you modify the rights so both @KaYBlitZ and I can publish if needed?  

Thanks

**Comment by AbdulRahmanAlHamali** [comment]
Hello
Thanks for the great work guys!
@sjmcdowall I added you as an uploader.
@KaYBlitZ can you remind me of your email please?

**Comment by KaYBlitZ** [comment]
Its kennethliang0@gmail.com

**Comment by AbdulRahmanAlHamali** [comment]
Done
