### ISSUE TITLE
Keep from reloading on navigate back to tab

### ISSUE THREAD

**Issue by wyklif** [AbdulRahmanAlHamali/flutter_pagewise#74]
Hi thanks for the wonderful library, i have a question, is there a way to not reload afresh the previously visited tabs?
thanks

**Comment by wyklif** [comment]
Solved this by converting my widgets to stateful widgets and using the AutomaticKeepAliveClientMixin thanks again for the wonderful library

**Comment by kevin4dhd** [comment]
where did you put AutomaticKeepAliveClientMixin? could you show me an example please
